export const projects = [
  {
    id: 1,
    name: "TrackFit",
    description: "Projec t2",
    demo: "https://immense-savannah-94600-01fc64ff673b.herokuapp.com/",
    repo: "https://github.com/nlopez39/TrackFit",
    img: "./images/localhost_3000_.png",
  },
  {
    id: 2,
    name: "ANA-MARKET",
    description: "Project 1",
    demo: "https://ana-market-eae58deca7b8.herokuapp.com/",
    repo: "https://github.com/nlopez39/ana-market",
    img: "./images/ana-market.png",
  },
  {
    id: 3,
    name: "Coding Quiz",
    description: "Project 3",
    demo: "https://nlopez39.github.io/Coding-Quiz/",
    repo: "https://github.com/nlopez39/Coding-Quiz",
    img: "./images/coding-quiz.png",
  },
  {
    id: 4,
    name: "Password Generator",
    description: "Project 4",
    demo: "https://nlopez39.github.io/Password-Generator/",
    repo: "https://github.com/nlopez39/Password-Generator",
    img: "./images/password-gen.png",
  },
  {
    id: 5,
    name: "Work Scheduler",
    description: "Project 5",
    demo: "https://nlopez39.github.io/Work-Scheduler/",
    repo: "https://github.com/nlopez39/Work-Scheduler",
    img: "./images/work-scheduler.png",
  },
  {
    id: 6,
    name: "Weather App",
    description: "Projec t6",
    demo: "https://nlopez39.github.io/Weather-App/",
    repo: "https://github.com/nlopez39/Weather-App",
    img: "./images/weather-app.png",
  },
];
